kokoro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    # admin site
    path('admin/', admin.site.urls),

    # include urls for users app
    path('users/', include('users.urls')),

    # include urls for kokoro_app
    path('', include('kokoro_app.urls')),

    # include urls for notifications app
    path('notifications/', include('notifications.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kokoro_app/urls.py
"""Defines URL patterns for kokoro_app"""

from django.urls import path

from . import views

app_name = 'kokoro_app'
urlpatterns = [
    # Landing Page
    path('', views.index, name='index'),

    # Home Page
    path('home/', views.home, name='home'),

    # User-Profile Page
    path('profile/', views.profile, name='profile'),

    # Page for editing profile & account settings
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    # Page for viewing a single post
    path('post/<slug:post_slug>/', views.post, name='post'),

    # Page for writing a new ProfilePost
    path('write_post/', views.write_post, name='write_post'),

    # Page for editing a ProfilePost object
    path('edit_post/', views.edit_post, name='edit_post'),

    # Page to display search results
    path('search/', views.search, name='search'),

    # Called when forms submitted from profile.html, redirects to profile()
    path('profile_form_handler/', views.profile_form_handler, name='profile_form_handler'),

    # Called when forms submitted from post.html & write_post.html, redirects to profile()
    path('posts_form_handler/', views.posts_form_handler, name='posts_form_handler'),

    # Called when send_friend_request_form submitted
    path('send_friendship_request_handler/<sending_to_id>/', views.send_friendship_request_handler, name='send_friendship_request_handler'),

    # Called when a user wants to accept a pending friendship request
    path('accept_friendship_request_handler/<sent_by>/', views.accept_friendship_request_handler, name='accept_friendship_request_handler'),

    # Called when a user wants to cancel a friendship request that they sent
    path('cancel_friendship_request_handler/<friendship_request>/', views.cancel_friendship_request_handler, name='cancel_friendship_request_handler'),

    # Called when a user wants to decline a friendship request that was sent to them
    path('decline_friendship_request_handler/<friendship_request>/', views.decline_friendship_request_handler, name='decline_friendship_request_handler'),

    # Page for viewing user's friendships
    path('view_friendships/', views.view_friendships, name='view_friendships'),

    # Called when user wants to remove a friendship with another user
    path('remove_friendship_handler/', views.remove_friendship_handler, name='remove_friendship_handler'),

    # Support page for contacting kokoro
    path('support/', views.support, name='support'),
]

notifications/urls.py
""" Defines URL patterns for notifications app """

from django.urls import path

from . import views

app_name = 'notifications'
print(app_name)

urlpatterns = [

    # Called when a Notification object needs to be altered
    path('notifications/notifications_form_handler/', views.notification_form_handler, name='notification_form_handler'),

]

users/urls.py
"""Defines url patterns for users"""

from django.urls import path, include
from . import views

# Distinguish 'users' urls from other app urls
app_name = 'users'
urlpatterns = [
    # Include the default django auth urls (login\logout)
    path('', include('django.contrib.auth.urls')),

    # Registration page for new users
    path('register/', views.register, name='register'),

    # Thank You page for newly-registered users
    path('thank_you/', views.thank_you, name='thank_you'),
]

kokoro_app/forms.py
from django import forms

from .models import Activity, PerfectBalance, ProfileBio, ProfileDisplayName, ProfileQuote,\
                    ProfileImage, ProfileTimezone, ContactInfo, ProfilePost, SupportReport

from cloudinary.forms import CloudinaryFileField

# Create forms based on defined models


class ActivityForm(forms.ModelForm):
    class Meta:
        model = Activity
        fields = ['activity', 'description']
        labels = {'description': ''}


class PerfectBalanceForm(forms.ModelForm):
    class Meta:
        model = PerfectBalance
        fields = ['perfect_mind', 'perfect_body', 'perfect_soul']


class ProfileBioForm(forms.ModelForm):
    class Meta:
        model = ProfileBio
        fields = ['biography']


class ProfileDisplayNameForm(forms.ModelForm):
    class Meta:
        model = ProfileDisplayName
        fields = ['display_name']


class ProfileQuoteForm(forms.ModelForm):
    class Meta:
        model = ProfileQuote
        fields = ['quote', 'quote_author']


class ProfileImageForm(forms.ModelForm):
    image = CloudinaryFileField(
        options={
            # change upload settings when needed
            'crop': 'thumb',
            'gravity': 'face',
            'width': 200,
            'height': 200,
            'folder': 'kokoro_images',
        }
    )

    class Meta:
        model = ProfileImage
        fields = ['image']


class ProfileTimezoneForm(forms.ModelForm):
    class Meta:
        model = ProfileTimezone
        fields = ['user_timezone']


class ContactInfoForm(forms.ModelForm):
    class Meta:
        model = ContactInfo
        fields = ['user_email']


class ProfilePostForm(forms.ModelForm):
    class Meta:
        model = ProfilePost
        fields = ['headline', 'content']


class SupportReportForm(forms.ModelForm):
    """
    Form for sending a support/help report to kokoro
    """

    class Meta:
        model = SupportReport
        fields = ['subject', 'body', 'contact_email', 'username']

kokoro_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.utils.crypto import get_random_string
from django.db import IntegrityError
from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponseRedirect

import cloudinary

from .models import Activity, PerfectBalance, ProfileBio, ProfileDisplayName, ProfileQuote, ProfileImage, \
                    ProfileTimezone, BalanceStreak, ContactInfo, ProfilePost, User, PinnedProfilePost,\
                    FriendshipRequest, Friendships

from .forms import ActivityForm, PerfectBalanceForm, ProfileBioForm, ProfileDisplayNameForm, \
                   ProfileQuoteForm, ProfileImageForm, ProfileTimezoneForm, ContactInfoForm, \
                   ProfilePostForm, SupportReportForm

from . import balance, profile_utils, friendship_utils
import pytz
import datetime
import os


def index(request):
    """Landing Page for Kokoro"""

    return render(request, 'kokoro_app/index.html', {})


@login_required()
def home(request):
    """Home Page for Kokoro users"""

    # Expire the user session on browser close ( 0 secs )
    request.session.set_expiry(0)

    if request.method == "POST":
        if 'activity_form' in request.POST:
            activity_form = ActivityForm(data=request.POST)
            if activity_form.is_valid():
                new_form = activity_form.save(commit=False)
                # title-ize activity
                new_form.description = new_form.description.title()
                # add owner
                new_form.owner = request.user
                new_form.save()
                return redirect('/home')

        elif 'manage_form' in request.POST:

            raw_post_data = request.POST

            # checkbox attrs are key=id_of_entry, value=on/off
            # By retrieving the key(s), we know what values to delete from database
            # '[1:len(result) - 1]' removes the csrf_token and button name from result
            post_data = list(raw_post_data.keys())[1:len(raw_post_data) - 1]

            # Delete objects based on their 'id' obtained from the queryDict/QueryList
            acts_to_delete = Activity.objects.filter(id__in=post_data)
            acts_to_delete.delete()
            return redirect('/home')

    # form for submitting daily activities
    activity_form = ActivityForm()

    activities = Activity.objects.filter(owner=request.user).order_by('date_added')

    # Returns all activities submitted today for user (queryset)
    start_of_today = balance.get_start_of_today(request)
    daily_mind = balance.daily_mind(request, start_of_today)
    daily_body = balance.daily_body(request, start_of_today)
    daily_soul = balance.daily_soul(request, start_of_today)

    # Package daily activities
    all_daily = {
        'daily_mind': daily_mind,
        'daily_body': daily_body,
        'daily_soul': daily_soul
    }

    # Returns boolean indicating if user has submitted at least 1 mind, body, and soul activity today
    # Also returns user balance streak
    balance_data = balance.balance(request, daily_mind, daily_body, daily_soul)
    found_balance = balance_data['found_balance']
    balance_streak = balance_data['balance_streak_value']

    context = {
        'activity_form': activity_form,
        'activities': activities,
        'all_daily': all_daily,
        'balance_bool': found_balance,
        'balance_streak': balance_streak
    }

    return render(request, 'kokoro_app/home.html', context)


@login_required
def profile(request):
    """
    Profile page for kokoro users
    :param request: request data
    :return: render of a user's profile page
    """

    # initial variables that aren't always reached
    already_friends = False
    pending_friendship_request = False

    if request.method == "POST":
        raise Http404("This shouldn't happen.")

    elif request.method == 'GET':

        # Get id of user profile to visit
        user_id = profile_utils.get_profile_to_visit(request)

        # user requesting their own profile
        if user_id == request.user.id:

            user = request.user

        # Get user object if user requesting a different profile than their own
        else:
            try:
                user = User.objects.get(id__exact=user_id)

            except Exception as e:
                raise Http404('Something went wrong while retrieving the profile you requested.', e)

            # determine if current user is already friends with the user that we're visiting (returns bool)
            already_friends = friendship_utils.determine_if_friends(request, user)

            # Check for pending friendship request if users are not friends (returns bool)
            if not already_friends:
                pending_friendship_request = friendship_utils.check_for_pending_friendship_request(request, user_id)

        # ----- user info/data for profile page -----
        # Note: some data can be accessed via 'user'
        profile_models = {
            'contact_info_model': ContactInfo,
            'post_model': ProfilePost,
            'pinned_post_model': PinnedProfilePost,
        }

        # Pass profile_models to helper (returns dictionary of user-specific data to build profile page)
        profile_data = profile_utils.get_profile_data(user, profile_models)

        # Retrieve TZ info separately, as we always want request.user's TZ data
        user_timezone_object, user_timezone = profile_utils.get_user_timezone(
            request.user, ProfileTimezone
        )

        for post in profile_data['posts']:
            date_published_utc = post.date_published
            date_published_user_tz = balance.convert_to_user_tz(date_published_utc, str(user_timezone_object))
            post.date_published = date_published_user_tz

        context = {
            'user': user,
            'already_friends': already_friends,
            'pending_friendship_request': pending_friendship_request,
            'contact_info': profile_data['contact_info'],  # Determine usage of contact info
            'posts': profile_data['posts'],
        }

        return render(request, 'kokoro_app/profile.html', context)


@login_required
def edit_profile(request):
    """
    Page for editing profile and account settings
    :param request: http data
    :return: render of edit_profile.html
    """

    user = request.user

    # *** MOVE to helper file
    # get UTC time with offset
    utc_timezone = datetime.datetime.now(tz=pytz.UTC)

    # get user's saved time zone
    user_timezone_object = user.profiletimezone
    # convert to string
    user_timezone_string = str(user_timezone_object)
    # convert utc_timezone to user timezone (with offset)
    user_timezone = utc_timezone.astimezone(pytz.timezone(user_timezone_string))

    # retrieve user-related objects as placeholders
    try:
        bio_placeholder = user.profilebio
    except ObjectDoesNotExist:
        bio_placeholder = None
    try:
        perfect_placeholder_queryset = user.perfectbalance
    except ObjectDoesNotExist:
        perfect_placeholder_queryset = None
    try:
        display_name_placeholder = user.profiledisplayname
    except ObjectDoesNotExist:
        display_name_placeholder = None
    try:
        quote_placeholder_queryset = user.profilequote
    except ObjectDoesNotExist:
        quote_placeholder_queryset = None
    try:
        contact_info = user.contactinfo
    except ObjectDoesNotExist:
        contact_info = None

    # Everyone has an image by default
    try:
        profile_image_placeholder = user.profileimage
    except ObjectDoesNotExist:
        profile_image_placeholder = None

    # Forms for editing profile
    display_name_form = ProfileDisplayNameForm(instance=display_name_placeholder)
    quote_form = ProfileQuoteForm(instance=quote_placeholder_queryset)
    bio_form = ProfileBioForm(instance=bio_placeholder)
    contact_form = ContactInfoForm(instance=contact_info)
    perfect_form = PerfectBalanceForm(instance=perfect_placeholder_queryset)
    profile_image_form = ProfileImageForm(instance=profile_image_placeholder)

    context = {
        'profile_image_form': profile_image_form,
        'profile_image_placeholder': profile_image_placeholder,
        'display_name_form': display_name_form,
        'display_name_placeholder': display_name_placeholder,
        'quote_form': quote_form,
        'quote_placeholder_queryset': quote_placeholder_queryset,
        'bio_form': bio_form,
        'bio_placeholder': bio_placeholder,
        'contact_info': contact_info,
        'contact_form': contact_form,
        'perfect_form': perfect_form,
        'perfect_placeholder_queryset': perfect_placeholder_queryset,
        'timezones': pytz.common_timezones,
        'user_timezone_object': user_timezone_object,
        'user_timezone': user_timezone,
    }

    return render(request, 'kokoro_app/edit_profile.html', context)


@login_required
def profile_form_handler(request):
    """
    Helper function for processing forms submitted from profile.html template
    :param request: http request data
    :return: A redirect to profile() view
    """

    if request.method == "POST":

        if 'tz_form' in request.POST:

            # timezone the user selected
            user_timezone_form = ProfileTimezoneForm(request.POST, instance=request.user.profiletimezone)
            # check validity and save
            if user_timezone_form.is_valid():
                user_timezone_form.save()

            return redirect('/profile')

        elif 'perfect_form' in request.POST:
            perfect_form_submitted = PerfectBalanceForm(data=request.POST)
            if perfect_form_submitted.is_valid():

                # retrieve user PerfectBalance object

kokoro_app/templates/kokoro_app/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>kokoro</title>

  {% load static %}
  <link rel="stylesheet" type="text/css" href="\static\kokoro_app\styles.css">
  <link rel="preconnect" href="https://fonts.gstatic.com">
  <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@501&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <!-- favicon -->
  <link rel="apple-touch-icon" sizes="180x180" href="\static\kokoro_app\favicon\apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="\static\kokoro_app\favicon\favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="\static\kokoro_app\favicon\favicon-16x16.png">
  <link rel="manifest" href="\static\kokoro_app\favicon\site.webmanifest">

</head>
<body>
  <!--new navbar-->
  <header>
    <h1 class="logo">kokoro</h1>
    <input type="checkbox" id="nav-toggle" class="nav-toggle">
    <nav>
      <ul>

        {% if user.is_authenticated %}
          <li><a tabindex="7" class="greeting">Hello, {{ request.user.username }}.</a></li>
          <li class="dropdown">
              <button class="dropdown-btn">Notifications</button>
              <div class="dropdown-content">
                {% for notification in notifications %}
                  {% if notification.unread == True %}
                  <!-- notification is unread -->
                  <form action="{% url 'notifications:notification_form_handler' %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="drop-noti" name="notification_form" value="{{ notification.id }}">{{ notification.message }}</button>
                  </form>
                  {% else %}
                  <!-- notification is not unread -->
                    <form action="{% url 'notifications:notification_form_handler' %}" method="post">
                      {% csrf_token %}
                      <button type="submit" class="drop-noti drop-noti-read" name="notification_form" value="{{ notification.id }}">{{ notification.message }}</button>
                    </form>
                  {% endif %}
                {% empty %}
                    <button class="drop-noti">No Notifications</button>
                {% endfor %}
                {% if notifications %}
                  <form action="{% url 'notifications:notification_form_handler' %}" method="post">
                    {% csrf_token %}
                    <button class="drop-noti drop-noti-read" name="mark_all_form">Mark All As Seen</button>
                  </form>
                  <form action="{% url 'notifications:notification_form_handler' %}" method="post">
                    {% csrf_token %}
                    <button class="drop-noti drop-noti-read" name="clear_all_form">Clear All</button>
                  </form>
                {% endif %}
              </div>
          </li>
          <li><a href="{% url 'kokoro_app:home' %}">Home</a></li>
          <li><a href="{% url 'kokoro_app:profile' %}">Profile</a></li>
          <li><a href="{% url 'users:logout' %}">Log Out</a></li>
          <li><a href="{% url 'kokoro_app:support' %}">Contact</a></li>
          <!--search bar-->
          <li>
            <form action="{% url 'kokoro_app:search' %}" method="get" autocomplete="off">
              <input class="nav-search font-med" type="text" name="search" placeholder="Search users"><button type="submit"><i class="fa fa-search search-icon"></i></button>
            </form>
          </li>
          <li><button class="theme-btn request-btn font-med" onclick="setThemePreference()">Change Theme</button></li>
        {% else %}
          <li><a href="{% url 'kokoro_app:home' %}">Home</a></li>
          <li><a href="{% url 'users:register' %}">Register</a></li>
          <li><a href="{% url 'users:login' %}">Log In</a></li>
          <li><a href="{% url 'kokoro_app:support' %}">Contact</a></li>
          <li><button class="theme-btn request-btn font-med" onclick="setThemePreference()">Change Theme</button></li>
        {% endif %}
      </ul>
    </nav>
    <label for="nav-toggle" class="nav-toggle-label">
        <span></span>
    </label>
  </header>
{% block content %}{% endblock content %}

<script>
// get root element
var root = document.querySelector(':root');
var rootStyles = getComputedStyle(root);

// we should also get <body>'s background-image
var body = document.querySelector('body');
var backgroundImage = body.style.backgroundImage;

// activity-card uses opacity, so we'll handle that separately
var activityCard = document.getElementsByClassName("activity-card-container")[0];

// set color variable values
// *** .getPropertyValue == '#05406D' only works if there is no space between color variable and its value (CSS) ***
// *** adding a space between --color-x and its value (CSS) requires putting a space before the hex in JS >>> ('--color-1') == ' #05406D'

function toggleLightTheme() {

    root.style.setProperty('--color-1', '#FAF8FF');
    root.style.setProperty('--color-2', '#FDFFFD');
    root.style.setProperty('--color-3', '#008500');
    root.style.setProperty('--color-4', '#005000');
    root.style.setProperty('--color-5', '#003000');
    root.style.setProperty('--color-6', 'black');
    root.style.setProperty('--color-7', '#003000');
    root.style.setProperty('--color-8', '#49BB49');
    root.style.setProperty('--color-9', '#49BB49');
    root.style.setProperty('--color-10', '#96FFA1');
    root.style.setProperty('--color-11', '#9A5A00');
    root.style.setProperty('--color-svg-shadow', '#A2FF98');

    body.style.setProperty('background-image', 'var(--svg-green-wave)');

    if (activityCard) {
        activityCard.style.background = 'rgba(255, 255, 255, .4)';
    }
}

function toggleDarkTheme() {

    root.style.setProperty('--color-1', '#05406D');
    root.style.setProperty('--color-2', '#043052');
    root.style.setProperty('--color-3', '#49BB49');
    root.style.setProperty('--color-4', '#F5A52D');
    root.style.setProperty('--color-5', 'white');
    root.style.setProperty('--color-6', 'black');
    root.style.setProperty('--color-7', 'lightgray');
    root.style.setProperty('--color-8', '#043052');
    root.style.setProperty('--color-9', '#FFFFFF');
    root.style.setProperty('--color-10', '#05406D');
    root.style.setProperty('--color-11', '#F5A52D');
    root.style.setProperty('--color-svg-shadow', '#F5A52D');

    body.style.setProperty('background-image', 'var(--svg-tan-wave)');

    if (activityCard) {
        activityCard.style.background = 'rgba(0, 0, 0, .4)';
    }
}

function setThemePreference() {
    // this function should first set localStorage themePreference, then call the appropriate toggle____Theme function
    if (localStorage.getItem("themePreference") === 'light' || localStorage.getItem("themePreference") == null) {

        localStorage.setItem("themePreference", "dark");
        toggleDarkTheme();
    }
    else {
        localStorage.setItem("themePreference", "light");
        toggleLightTheme();
    }
}

// called before page load to determine if dark theme should be applied
function applyThemePreference() {
    if (localStorage.getItem("themePreference") === 'dark') {
        toggleDarkTheme();
    }
}

applyThemePreference();
</script>
</body>
</html>

kokoro_app/templates/kokoro_app/edit_post.html
{% extends 'kokoro_app/base.html' %}

{% block content %}
<div class="super-container">
    <div class="post-container">
        <span class="post-form-header">Edit Post</span>
        <span class="write-header font-small">Make changes to your post and press 'Confirm Changes'</span>
        <br>
        <br>
        <form action="{% url 'kokoro_app:edit_post' %}" method="post">
            {% csrf_token %}
            <span class="font-large">Headline</span>
            <span class="post-form-headline">{{ post_form.headline }}</span>
            <span class="font-med">Body</span>
            <span class="post-form-content">{{ post_form.content }}</span>
            <button class="request-btn font-large" type="submit" name="update_post_form" value="{{ post_to_edit.post_slug }}">Confirm Changes</button>
        </form>
    </div>
</div>
{% endblock content %}

kokoro_app/templates/kokoro_app/profile.html
{% extends 'kokoro_app/base.html' %}

{% block content %}

{% load tz %}
{% load cloudinary %}
{% localtime off %}
<div class="profile-wrapper">
    <!-- container grid holding all-grids -->
    <div class="profile-grid-master">
        <!-- this grid contains profile_photo and profile_quote -->
        <div class="profile-grid-header">
            <div class="profile-image">
                {% if user.profileimage.image %}
                    <!-- get profile image from cloudinary -->
                    {% cloudinary user.profileimage.image %}
                {% else  %}
                    {% cloudinary 'https://res.cloudinary.com/getkokoro/image/upload/v1624223175/kokoro_images/default.png' type="fetch" %}
                {% endif %}
            </div>
            <div class="profile-quote-container">
                {% if user.profilequote.quote %}
                <div>
                    <span class="profile-quote-content font-med">
                        "{{ user.profilequote.quote }}"
                        <span class="profile-quote-author font-small">
                            - {{ user.profilequote.quote_author }}
                        </span>
                    </span>
                </div>
                {% else %}
                <div>
                    <span class="profile-quote-content font-med">
                        This user has not yet submitted a quote.
                        <span class="profile-quote-author font-small">
                            - kokoro
                        </span>
                    </span>
                </div>
                {% endif %}
            </div>
        </div>
        <div class="profile-name-grid">
            {% if user.profiledisplayname.display_name %}
                <span class="profile-display-name">{{ user.profiledisplayname.display_name }}</span>
            {% else %}
                <span class="profile-display-name">{{ user.username }}</span>
            {% endif %}
            {% if user == request.user %}
                <form class="edit-profile-form" action="{% url 'kokoro_app:edit_profile' %}" method="get">
                    <button class="edit-profile-or-friendship-btn font-small" type="submit">Edit Profile</button>
                </form>
            {% else %}
                {% if already_friends %}
                    <form class="edit-profile-form" action="{% url 'kokoro_app:view_friendships' %}">
                        <button type="submit" class="edit-profile-or-friendship-btn font-small">Friends</button>
                    </form>
                {% else %}
                    {% if pending_friendship_request == True %}
                        <form class="edit-profile-form" action="{% url 'kokoro_app:view_friendships' %}" method="get">
                            {% csrf_token %}
                            <button class="edit-profile-or-friendship-btn font-small" type="submit" name="view_friendships_form">
                                Pending...
                            </button>
                        </form>
                    {% else %}
                        <form class="edit-profile-form" action="{% url 'kokoro_app:send_friendship_request_handler' sending_to_id=user.id %}" method="post">
                            {% csrf_token %}
                            <button class="edit-profile-or-friendship-btn font-small" type="submit" name="send_friendship_request_form" value="{{ user }}">
                                Request Friendship
                            </button>
                        </form>
                    {% endif %}
                {% endif %}
            {% endif %}
            <span class="profile-username font-large">@{{ user }}</span>
        </div>
        <div class="profile-biography font-large">
            <span>{{ user.profilebio.biography }}</span>
        </div>
        {% if user.perfectbalance.perfect_mind %}
            <div class="perfect-balance-header">Perfect Balance</div>
            <div class="profile-perfect-balance">
                <span class="perfect-mind">{{ user.perfectbalance.perfect_mind }}</span><br>
                <span class="perfect-body">{{ user.perfectbalance.perfect_body }}</span><br>
                <span class="perfect-soul">{{ user.perfectbalance.perfect_soul }}</span>
            </div>
        {% endif %}
        {% if already_friends or user == request.user %}
            <div class="profile-contact">
                <span>{{ contact_info }}</span>
            </div>
        {% endif %}
        <!-- only for when viewing own profile -->
        <br>
        {% if user == request.user %}
            <div class="friendship-btn">
                <div>
                    <form action="{% url 'kokoro_app:view_friendships' %}" method="get">
                        <button class="friendship-btn-submit" type="submit">
                            View Friendships
                        </button>
                    </form>
                </div>
            </div>
            <div class="write-post-btn">
                <form action="{% url 'kokoro_app:write_post' %}" method="get">
                    <button class="write-post-btn-submit" type="submit">
                        Write a Post
                    </button>
                </form>
            </div>
        {% endif %}
        <!-- end viewing own profile -->
        <span class="profile-post-label">Posts</span>
        <div class="profile-post-prefix"></div>
        <div class="profile-post-container">
            {% for post in posts %}
                {% if post.post_slug %}
                    <!-- post == ProfilePost object -->
                    <form class="profile-post" action="{% url 'kokoro_app:post' post.post_slug %}" method="get">
                        <button type="submit">
                            <span class="profile-post-headline font-xl">{{ post.headline }}</span>
                            <span class="profile-post-author font-med">- {{ post.author }}</span>
                            <span class="post-date font-med">{{ post.date_published }}</span>
                        </button>
                    </form>
                    <div class="post-separator"></div>
                {% else %}
                    <!-- post == PinnedProfilePost object -->
                    <form class="profile-post" action="{% url 'kokoro_app:post' post.original.post_slug %}" method="get">
                        <button type="submit">
                            <span class="profile-pinned-message font-small">*pinned</span>
                            <span class="profile-post-headline profile-post-headline-pinned font-xl">{{ post.original.headline }}</span>
                            <span class="profile-post-author font-med">- {{ post.original.author }}</span>
                            <span class="post-date font-med">{{ post.date_published }}</span>
                        </button>
                    </form>
                    <div class="post-separator"></div>
                {% endif %}
            {% empty %}
                <div class="profile-post">
                    <button>
                        <span class="profile-post-headline font-xl" style="margin-top: 3rem;">{{ user }} hasn't created a post yet.</span>
                    </button>
                </div>
            {% endfor %}
            <br>
        </div>
        <div class="profile-post-prefix"></div>
    </div>
</div>
<div class="profile-bottom-pad"></div>
{% endlocaltime %}
{% endblock content %}